export const NOTIFICATION_EVENTS = {
  SERVICE_REQUEST_CREATED: 'SERVICE_REQUEST_CREATED',
  SERVICE_REQUEST_UNDER_REVIEW: 'SERVICE_REQUEST_UNDER_REVIEW',
  APPOINTMENT_REQUEST_RECEIVED: 'APPOINTMENT_REQUEST_RECEIVED',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER_T_MINUS_24H: 'APPOINTMENT_REMINDER_T_MINUS_24H',
  APPOINTMENT_REMINDER_T_MINUS_2H: 'APPOINTMENT_REMINDER_T_MINUS_2H',
  APPOINTMENT_NO_SHOW_FOLLOWUP: 'APPOINTMENT_NO_SHOW_FOLLOWUP',
  JOB_CARD_CREATED: 'JOB_CARD_CREATED',
  ESTIMATE_PREPARED: 'ESTIMATE_PREPARED',
  ESTIMATE_APPROVAL_REQUESTED: 'ESTIMATE_APPROVAL_REQUESTED',
  ESTIMATE_APPROVED: 'ESTIMATE_APPROVED',
  ESTIMATE_REJECTED: 'ESTIMATE_REJECTED',
  PARTS_DELAYED: 'PARTS_DELAYED',
  WORK_STARTED: 'WORK_STARTED',
  WORK_IN_PROGRESS_UPDATE: 'WORK_IN_PROGRESS_UPDATE',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  PARTIAL_PAYMENT_RECEIVED: 'PARTIAL_PAYMENT_RECEIVED',
  FULL_PAYMENT_RECEIVED: 'FULL_PAYMENT_RECEIVED',
  UNPAID_INVOICE_REMINDER: 'UNPAID_INVOICE_REMINDER',
  POST_SERVICE_FEEDBACK_REQUEST: 'POST_SERVICE_FEEDBACK_REQUEST',
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

export interface NotificationPayload {
  eventType: NotificationEventType;
  recipientPhone?: string;
  recipientEmail?: string;
  variables: Record<string, string>;
  relatedEntityType?: string;
  relatedEntityId?: string;
  createdByAdminId?: string;
  scheduledFor?: Date;
}
