#!/usr/bin/env bash
# Local launchd wrapper for scripts/db-backup.sh — daily cron on macOS.
#
# Usage:
#   ./scripts/db-backup-launchd.sh install      → install + load the launchd job
#   ./scripts/db-backup-launchd.sh uninstall    → unload + remove
#   ./scripts/db-backup-launchd.sh status       → show whether it's loaded
#   ./scripts/db-backup-launchd.sh run-now      → trigger once immediately
#
# The launchd job runs daily at 03:00 local time (deliberately offset from
# the GitHub Action's 02:00 UTC = 07:30 IST so both tiers don't depend on
# the same wall-clock moment).
#
# Logs land in backups/.launchd.log (stdout) and backups/.launchd.err (stderr).

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PLIST_NAME="ai.sgnk.gearup.db-backup"
PLIST_PATH="${HOME}/Library/LaunchAgents/${PLIST_NAME}.plist"
WRAPPER="${REPO}/scripts/db-backup-launchd-wrapper.sh"

write_wrapper() {
  # 'EOF' quoted so the shell does NOT pre-expand $VAR / ${k} / $(...) inside.
  # Only REPO_PLACEHOLDER is substituted afterwards via sed.
  cat > "$WRAPPER" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/db-backup-launchd.sh — do not edit by hand.
#
# We can't 'source .env' safely because real .env files contain unquoted
# values with spaces (e.g. NEXT_PUBLIC_APP_NAME=GearUp Servicing) and special
# chars in connection strings that break shell parsing. We use a tiny inline
# Node loader (dotenv) to populate env, then exec the backup script.
set -eo pipefail
cd "REPO_PLACEHOLDER"

# Parse .env via dotenv (already a dep of the web app) and emit shell exports.
if [ -f .env ]; then
  EXPORT_LINES=$(node -e "
    const dotenv = require('./apps/web/node_modules/dotenv');
    const out = dotenv.parse(require('fs').readFileSync('.env'));
    for (const [k, v] of Object.entries(out)) {
      // POSIX-safe single-quoted exports; embedded ' becomes '\\''
      const safe = String(v).replace(/'/g, \"'\\\\''\");
      console.log(\`export \${k}='\${safe}'\`);
    }
  ")
  eval "$EXPORT_LINES"
fi

exec ./scripts/db-backup.sh
EOF
  # Substitute the repo path placeholder. Pipe-delimited so a / in REPO is fine.
  sed -i.bak "s|REPO_PLACEHOLDER|${REPO}|g" "$WRAPPER"
  rm -f "${WRAPPER}.bak"
  chmod +x "$WRAPPER"
}

write_plist() {
  cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>            <string>${PLIST_NAME}</string>
    <key>ProgramArguments</key> <array><string>${WRAPPER}</string></array>
    <key>WorkingDirectory</key> <string>${REPO}</string>
    <key>StartCalendarInterval</key>
      <dict>
        <key>Hour</key>   <integer>3</integer>
        <key>Minute</key> <integer>0</integer>
      </dict>
    <key>RunAtLoad</key>      <false/>
    <key>StandardOutPath</key> <string>${REPO}/backups/.launchd.log</string>
    <key>StandardErrorPath</key><string>${REPO}/backups/.launchd.err</string>
    <key>EnvironmentVariables</key>
      <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/opt/homebrew/opt/postgresql@17/bin:/usr/local/bin:/usr/bin:/bin</string>
      </dict>
  </dict>
</plist>
EOF
}

case "${1:-}" in
  install)
    mkdir -p "${HOME}/Library/LaunchAgents" "${REPO}/backups"
    write_wrapper
    write_plist
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    launchctl load "$PLIST_PATH"
    echo "Installed ${PLIST_NAME}. Will run daily at 03:00 local."
    echo "Logs: ${REPO}/backups/.launchd.log (stdout), .launchd.err (stderr)"
    ;;
  uninstall)
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    rm -f "$PLIST_PATH" "$WRAPPER"
    echo "Uninstalled ${PLIST_NAME}."
    ;;
  status)
    if [ -f "$PLIST_PATH" ]; then
      echo "Plist installed at: $PLIST_PATH"
      launchctl list | grep -E "${PLIST_NAME}" || echo "(not currently loaded)"
    else
      echo "Not installed."
    fi
    ;;
  run-now)
    if [ ! -x "$WRAPPER" ]; then
      echo "Not installed — run ./scripts/db-backup-launchd.sh install first" >&2
      exit 1
    fi
    "$WRAPPER"
    ;;
  *)
    echo "Usage: $0 {install|uninstall|status|run-now}" >&2
    exit 64
    ;;
esac
