-- gearup data-quality fixes — generated 2026-06-11T21:22:52.788854+00:00
-- POLICY: INSERT + UPDATE only. ZERO DELETE statements.
-- Idempotent: ON CONFLICT DO NOTHING / guarded UPDATEs.
BEGIN;
SET session_replication_role = replica;

-- 1. Restore 3 June-10 job cards (full cache rows)
INSERT INTO public."JobCard" ("id", "jobCardNumber", "appointmentId", "serviceRequestId", "customerId", "vehicleId", "intakeDate", "odometerAtIntake", "fuelIndicator", "estimatedDeliveryAt", "actualDeliveryAt", "issueSummary", "customerComplaints", "diagnosisNotes", "estimateNotes", "approvalStatus", "priority", "status", "assignedServiceManagerId", "estimatedPartsCost", "estimatedLaborCost", "estimatedOtherCost", "estimatedTotal", "finalPartsCost", "finalLaborCost", "finalOtherCost", "finalTotal", "customerVisibleNotes", "internalNotes", "estimateToken", "estimateTokenExpiresAt", "estimateRevision", "createdAt", "updatedAt") VALUES ('cmq7qst7k004capw7b35euq52', 'JC-GPXCDSM0', NULL, NULL, 'cmq7qqv650040apw7cxysd389', 'cmq7qrmte0048apw7byln132t', '2026-06-10T07:23:48.297Z', 4565, '1/2', NULL, '2026-06-10T09:58:33.253Z', 'FOAM WASH
MOBIL CHANGE
CHAIN CLEAN CHAIN LUBE', '', NULL, NULL, 'PENDING', '', 'DELIVERED', NULL, '0', '0', '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, '2026-06-10T07:23:48.298Z', '2026-06-10T09:58:33.254Z') ON CONFLICT DO NOTHING;
INSERT INTO public."JobCard" ("id", "jobCardNumber", "appointmentId", "serviceRequestId", "customerId", "vehicleId", "intakeDate", "odometerAtIntake", "fuelIndicator", "estimatedDeliveryAt", "actualDeliveryAt", "issueSummary", "customerComplaints", "diagnosisNotes", "estimateNotes", "approvalStatus", "priority", "status", "assignedServiceManagerId", "estimatedPartsCost", "estimatedLaborCost", "estimatedOtherCost", "estimatedTotal", "finalPartsCost", "finalLaborCost", "finalOtherCost", "finalTotal", "customerVisibleNotes", "internalNotes", "estimateToken", "estimateTokenExpiresAt", "estimateRevision", "createdAt", "updatedAt") VALUES ('cmq7p0x85000guec9q1y852bp', 'JC-L2ZLL3J3', NULL, NULL, 'cmq7oxyua0004uec9ri6xvuea', 'cmq7oz5na000cuec9uma5fdn3', '2026-06-10T06:34:07.502Z', 5500, '1/2', NULL, '2026-06-10T07:36:02.468Z', 'FOAM WASH 
GEAR CHECK 
UPER LIGHT 
STAND SENSOR PROBLEM ', '', NULL, NULL, 'PENDING', '', 'DELIVERED', NULL, '0', '0', '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, '2026-06-10T06:34:07.504Z', '2026-06-10T07:36:02.469Z') ON CONFLICT DO NOTHING;
INSERT INTO public."JobCard" ("id", "jobCardNumber", "appointmentId", "serviceRequestId", "customerId", "vehicleId", "intakeDate", "odometerAtIntake", "fuelIndicator", "estimatedDeliveryAt", "actualDeliveryAt", "issueSummary", "customerComplaints", "diagnosisNotes", "estimateNotes", "approvalStatus", "priority", "status", "assignedServiceManagerId", "estimatedPartsCost", "estimatedLaborCost", "estimatedOtherCost", "estimatedTotal", "finalPartsCost", "finalLaborCost", "finalOtherCost", "finalTotal", "customerVisibleNotes", "internalNotes", "estimateToken", "estimateTokenExpiresAt", "estimateRevision", "createdAt", "updatedAt") VALUES ('cmq7nflt70017jlikr9lkccav', 'JC-QU94NCZW', NULL, NULL, 'cmq7ndm3g0000apw7w03bjqg9', 'cmq7nepr80004apw7r65jaxq4', '2026-06-10T05:49:33.350Z', 8862, '3/4', NULL, '2026-06-10T07:20:41.553Z', 'Foam Wash 
Mobil change 
Chain clean and chain lube', '', NULL, NULL, 'PENDING', '', 'DELIVERED', NULL, '0', '0', '0', '0', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, '2026-06-10T05:49:33.351Z', '2026-06-10T07:20:41.554Z') ON CONFLICT DO NOTHING;

-- 2. AppointmentSlotRule from dump (6)
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ejrxv004atk9w72n7mu17', '1', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:37.556', '2026-06-10 18:28:37.556') ON CONFLICT DO NOTHING;
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ejsj6004btk9w3a2g5bas', '2', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:38.323', '2026-06-10 18:28:38.323') ON CONFLICT DO NOTHING;
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ejt36004ctk9wwz0w5cam', '3', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:39.042', '2026-06-10 18:28:39.042') ON CONFLICT DO NOTHING;
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ejtn4004dtk9wvyq7jwu0', '4', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:39.76', '2026-06-10 18:28:39.76') ON CONFLICT DO NOTHING;
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8eju74004etk9wfns1bqw7', '5', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:40.48', '2026-06-10 18:28:40.48') ON CONFLICT DO NOTHING;
INSERT INTO public."AppointmentSlotRule" ("id", "dayOfWeek", "openTime", "closeTime", "slotDurationMinutes", "maxCapacity", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ejur6004ftk9wg635h205', '6', '09:00', '18:00', '30', '3', 't', '2026-06-10 18:28:41.202', '2026-06-10 18:28:41.202') ON CONFLICT DO NOTHING;

-- 2. NotificationTemplate from dump (4)
INSERT INTO public."NotificationTemplate" ("id", "channel", "eventType", "templateKey", "subject", "messageBody", "variableSchemaJson", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ekbqb005ftk9w5guejdud', 'WHATSAPP', 'appointment.confirmed', 'appt_confirmed_wa', NULL, 'Hi {{customerName}}, your appointment on {{date}} at {{time}} is confirmed. Ref: {{referenceId}}', NULL, 't', '2026-06-10 18:29:03.203', '2026-06-10 18:29:03.203') ON CONFLICT DO NOTHING;
INSERT INTO public."NotificationTemplate" ("id", "channel", "eventType", "templateKey", "subject", "messageBody", "variableSchemaJson", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ekcah005gtk9woaqmigfg', 'EMAIL', 'appointment.confirmed', 'appt_confirmed_email', 'Appointment Confirmed', 'Dear {{customerName}}, your appointment is confirmed for {{date}}.', NULL, 't', '2026-06-10 18:29:03.929', '2026-06-10 18:29:03.929') ON CONFLICT DO NOTHING;
INSERT INTO public."NotificationTemplate" ("id", "channel", "eventType", "templateKey", "subject", "messageBody", "variableSchemaJson", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ekcuk005htk9wvcj5pwkb', 'WHATSAPP', 'jobcard.ready', 'jc_ready_wa', NULL, 'Hi {{customerName}}, your {{vehicleReg}} is ready for pickup! Job Card: {{jobCardNumber}}', NULL, 't', '2026-06-10 18:29:04.653', '2026-06-10 18:29:04.653') ON CONFLICT DO NOTHING;
INSERT INTO public."NotificationTemplate" ("id", "channel", "eventType", "templateKey", "subject", "messageBody", "variableSchemaJson", "isActive", "createdAt", "updatedAt") VALUES ('cmq8ekdep005itk9w6pwn1mxk', 'EMAIL', 'invoice.created', 'invoice_email', 'Invoice {{invoiceNumber}}', 'Dear {{customerName}}, your invoice {{invoiceNumber}} for ₹{{amount}} is ready.', NULL, 't', '2026-06-10 18:29:05.377', '2026-06-10 18:29:05.377') ON CONFLICT DO NOTHING;

-- 3/5. WhatsApp-documented invoice line items (guarded: only if invoice has zero lines)
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invzv6ga74k_01', i.id, 'SERVICE_CHARGE', NULL, 'General Service', 1, 350, 0, 0, 0, 350, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-ZV6GA74K' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invzv6ga74k_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invzv6ga74k_02', i.id, 'SERVICE_CHARGE', NULL, 'DAMPER RUBBER', 1, 135, 5, 0, 0, 128.25, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-ZV6GA74K' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invzv6ga74k_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invirfv45y9_01', i.id, 'SERVICE_CHARGE', NULL, '5100 ENGINE OIL 10W30 1 LTR', 1, 695, 0, 0, 0, 695, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-IRFV45Y9' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invirfv45y9_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invirfv45y9_02', i.id, 'LABOR', NULL, 'Labor - HARADHAN GOSWAMI', 1, 350, 0, 0, 0, 350, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-IRFV45Y9' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invirfv45y9_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invirfv45y9_03', i.id, 'SERVICE_CHARGE', NULL, 'FOAM WASH', 1, 49, 0, 0, 0, 49, 3 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-IRFV45Y9' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invirfv45y9_03') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invddt1skbt_01', i.id, 'SERVICE_CHARGE', NULL, 'CHAIN CLEAN AND CHAIN LUBE', 1, 140, 0, 0, 0, 140, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-DDT1SKBT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invddt1skbt_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invddt1skbt_02', i.id, 'LABOR', NULL, 'Labor - SOUVIK MUSI', 1, 49, 0, 0, 0, 49, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-DDT1SKBT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invddt1skbt_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invddt1skbt_03', i.id, 'SERVICE_CHARGE', NULL, 'ENFIELD ENGINE OIL 2.50L', 1, 1050, 5, 0, 0, 997.5, 3 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-DDT1SKBT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invddt1skbt_03') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_01', i.id, 'LABOR', NULL, 'Labor - AMIT PAL', 1, 350, 0, 0, 0, 350, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_02', i.id, 'SERVICE_CHARGE', NULL, '597204 BALL RACE KIT', 1, 489, 5, 0, 0, 464.55, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_03', i.id, 'SERVICE_CHARGE', NULL, '1100693/B ABS WHEEL SPEEDO SENSOR', 1, 530, 5, 0, 0, 503.5, 3 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_03') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_04', i.id, 'SERVICE_CHARGE', NULL, '8881148 c.s. kit', 1, 1982, 5, 0, 0, 1882.9, 4 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_04') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_05', i.id, 'SERVICE_CHARGE', NULL, '570416/N GASKET COVER RH', 1, 66, 5, 0, 0, 62.7, 5 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_05') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_06', i.id, 'SERVICE_CHARGE', NULL, 'KAB00246/A BRAKE PAD KIT', 1, 267, 5, 0, 0, 253.65, 6 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_06') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_07', i.id, 'SERVICE_CHARGE', NULL, '592281/A BRAKE LEVER', 1, 152, 5, 0, 0, 144.4, 7 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_07') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_08', i.id, 'SERVICE_CHARGE', NULL, '594631 MASTER CYLINDER ASSY', 1, 1380, 5, 0, 0, 1311, 8 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_08') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_09', i.id, 'SERVICE_CHARGE', NULL, 'disc oil top up', 1, 50, 0, 0, 0, 50, 9 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_09') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_10', i.id, 'SERVICE_CHARGE', NULL, 'NUMBER PLATE FRAME REFLECCOR', 1, 40, 0, 0, 0, 40, 10 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_10') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_11', i.id, 'LABOR', NULL, 'HANDLE RACER CHANGE LABOR', 1, 180, 0, 0, 0, 180, 11 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_11') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invhjr180k5_12', i.id, 'LABOR', NULL, 'CHAIN SPOKET LABOR CHARGE', 1, 280, 0, 0, 0, 280, 12 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-HJR180K5' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invhjr180k5_12') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invl4a9dq49_01', i.id, 'SERVICE_CHARGE', NULL, 'FOAM WASH', 1, 49, 0, 0, 0, 49, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-L4A9DQ49' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invl4a9dq49_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invl4a9dq49_02', i.id, 'SERVICE_CHARGE', NULL, 'CABLE ADJUSTMENT CHARGE', 1, 20, 0, 0, 0, 20, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-L4A9DQ49' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invl4a9dq49_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invl4a9dq49_03', i.id, 'SERVICE_CHARGE', NULL, 'WASHING CHARGE', 1, 49, 0, 0, 0, 49, 3 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-L4A9DQ49' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invl4a9dq49_03') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invkbx396bt_01', i.id, 'SERVICE_CHARGE', NULL, '3000 4T PLUS ENGINE OIL 10W30 900ML', 1, 425, 6, 0, 0, 399.5, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-KBX396BT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invkbx396bt_01') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invkbx396bt_02', i.id, 'SERVICE_CHARGE', NULL, 'SBZ MINDA BUZZER', 1, 41, 0, 0, 0, 41, 2 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-KBX396BT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invkbx396bt_02') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_invkbx396bt_03', i.id, 'LABOR', NULL, 'Labor - HARADHAN GOSWAMI', 1, 350, 0, 0, 0, 350, 3 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-KBX396BT' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_invkbx396bt_03') ON CONFLICT DO NOTHING;
INSERT INTO public."InvoiceLineItem" ("id","invoiceId","lineType","referenceItemId",description,quantity,"unitPrice","discountPercent","taxRate","taxAmount","lineTotal","sortOrder") SELECT 'recov_inv2slmsr6x_01', i.id, 'LABOR', NULL, 'Labor - HARADHAN GOSWAMI', 1, 370, 0, 0, 0, 370, 1 FROM public."Invoice" i WHERE i."invoiceNumber" = 'INV-2SLMSR6X' AND NOT EXISTS (SELECT 1 FROM public."InvoiceLineItem" x WHERE x."invoiceId" = i.id AND x.id <> 'recov_inv2slmsr6x_01') ON CONFLICT DO NOTHING;

-- 3b. INV-HJR180K5 (Avijit Mondal): totals + PAID, per WhatsApp tax invoice
UPDATE public."Invoice" SET subtotal = 5522.70, "grandTotal" = 5523.00, "amountPaid" = 5523.00, "amountDue" = 0, "paymentStatus" = 'PAID' WHERE "invoiceNumber" = 'INV-HJR180K5' AND "grandTotal" = 0;

-- 4. AMC zero-value invoices: UNPAID -> PAID per app status rule
UPDATE public."Invoice" SET "paymentStatus" = 'PAID' WHERE "invoiceNumber" IN ('INV-WE7T7ZRO','INV-NPOM2A35','INV-WHAMH0CM') AND "grandTotal" = 0 AND "amountDue" = 0 AND "paymentStatus" = 'UNPAID';

-- 6. Clear phantom reservations (reserved > stock; reset-era leftovers). Stock counts untouched.
UPDATE public."InventoryItem" SET "reservedQuantity" = 0 WHERE id IN ('cmpw6yi0a000110c9vssu3o93','cmpxt0wnd000ny7wyt2ytbej4','cmpw473ck0007u7s3zup66pcw','cmpw4ha0g001zu7s3xfktrzv9') AND "reservedQuantity" > "quantityInStock";

SET session_replication_role = DEFAULT;
COMMIT;
